# Window settings
[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

# Font settings
[font]
# Use Agave Nerd Font as the default family
normal.family = "Agave Nerd Font"
bold.family = "Agave Nerd Font"
italic.family = "Agave Nerd Font"
bold_italic.family = "Agave Nerd Font"


# Font size
size = 16

